### ISSUE TITLE
Include the addition of "ngCpfCnpj" module on documentation

### ISSUE THREAD

**Issue by leonardoquevedox** [gil/ng-cpf-cnpj#5]
The documentation does not mention that you should include the ngCpfCnpj within the other AngularJS modules, something like:
"var app = angular.module(myApplicationName, [ "cordovaHTTP", "ngMask", "ngRoute", "ngCpfCnpj" ])";

I know that it's something pretty obvious, but it may confuse some beginner developers.

**Comment by gil** [comment]
I've just merged PR #4 with that fix. Sorry for the mistake and for taking so long to reply!
