### ISSUE TITLE
congelado?

### ISSUE THREAD

**Issue by awerlang** [gil/ng-cpf-cnpj#6]
O repositório existe há 18 meses e parou desde então. Ainda assim considero a melhor implementação do tipo.

Porém precisa se adequar ao v1.3, que introduziu o `ngModelOptions` na api. A versão do PR #2 parece ser um passo na direção certa, porém o correto para a v1.3 é usar `ngModelController#validators`.

Acho que seria interessante revisar os PRs abertos. Alguma previsão?

**Comment by gil** [comment]
Opa, desculpe pela demora :disappointed: Tive alguns problemas recentemente e, na correria, acabei deixando muita coisa sem atenção. Vou revisar tudo no final de semana e dou uma resposta logo!

**Comment by awerlang** [comment]
Show de bola. Qualquer coisa prende o grito!

**Comment by gil** [comment]
Finalmente fiz merge dos PRs que faziam sentido e fiz a mudança do ngModelController#validators, com fallback de ngModelController#parsers para suportar Angular <= 1.2.

Publiquei a version 0.0.5. Qualquer coisa dá um grito! ;)

**Comment by awerlang** [comment]
:+1:
